version: "3.8"

services:

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle

  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8081"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/orclpdb
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus